version: '3.1'

services:

  db:
    image: postgres:12.4-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: userpass
      POSTGRES_USER: user
